
package org.seasar.remoting.axis2.examples.jaxws.ex02.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Calc", targetNamespace = "http://ex02.jaxws.examples.axis2.remoting.seasar.org/")
public interface Calc {


    /**
     * 
     * @param value1
     * @param value2
     * @return
     *     returns int
     */
    @WebMethod(action = "add")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ex02.jaxws.examples.axis2.remoting.seasar.org/", className = "org.seasar.remoting.axis2.examples.jaxws.ex02.client.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ex02.jaxws.examples.axis2.remoting.seasar.org/", className = "org.seasar.remoting.axis2.examples.jaxws.ex02.client.AddResponse")
    public int add(
        @WebParam(name = "value1", targetNamespace = "")
        int value1,
        @WebParam(name = "value2", targetNamespace = "")
        int value2);

}
