/*
 * Copyright 2004-2010 the Seasar Foundation and the Others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package org.seasar.remoting.axis2.examples.jaxws.ex02.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Calc", targetNamespace = "http://ex02.jaxws.examples.axis2.remoting.seasar.org/")
public interface Calc {


    /**
     * 
     * @param value1
     * @param value2
     * @return
     *     returns int
     */
    @WebMethod(action = "add")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ex02.jaxws.examples.axis2.remoting.seasar.org/", className = "org.seasar.remoting.axis2.examples.jaxws.ex02.client.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ex02.jaxws.examples.axis2.remoting.seasar.org/", className = "org.seasar.remoting.axis2.examples.jaxws.ex02.client.AddResponse")
    public int add(
        @WebParam(name = "value1", targetNamespace = "")
        int value1,
        @WebParam(name = "value2", targetNamespace = "")
        int value2);

}
