/*
 * Copyright 2004-2009 the Seasar Foundation and the Others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */
package org.seasar.remoting.axis2.examples.jaxws.ex02.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "CalcService", targetNamespace = "http://ex02.jaxws.examples.axis2.remoting.seasar.org/", wsdlLocation = "http://localhost:8080/s2axis2-examples/services/CalcService.CalculatorServicePort?wsdl")
public class CalcService
    extends Service
{

    private final static URL CALCSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/s2axis2-examples/services/CalcService.CalculatorServicePort?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CALCSERVICE_WSDL_LOCATION = url;
    }

    public CalcService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalcService() {
        super(CALCSERVICE_WSDL_LOCATION, new QName("http://ex02.jaxws.examples.axis2.remoting.seasar.org/", "CalcService"));
    }

    /**
     * 
     * @return
     *     returns Calc
     */
    @WebEndpoint(name = "CalculatorServicePort")
    public Calc getCalculatorServicePort() {
        return (Calc)super.getPort(new QName("http://ex02.jaxws.examples.axis2.remoting.seasar.org/", "CalculatorServicePort"), Calc.class);
    }

}
